// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingNerdAPI.Model.Context;

#nullable disable

namespace ShoppingNerdAPI.Migrations
{
    [DbContext(typeof(MysqlContext))]
    partial class MysqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingNerdAPI.Model.Base.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CategoriaNome");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Preco");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Categoria = "Vestimenta",
                            Descricao = "Calça Slim",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.aswracing.com.br%2Fcalca-asw-image-minimal-23-a1048723-p4013646&psig=AOvVaw1isNPh-QwGdSv-p919sBfC&ust=1685672108553000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIiL64qAof8CFQAAAAAdAAAAABAE",
                            Nome = "Calça",
                            Preco = 69.2m
                        },
                        new
                        {
                            Id = 3L,
                            Categoria = "Esporte",
                            Descricao = "Bola Futebol",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Focfc.com.br%2Fproduto%2Fbola-futebol-adidas-uefa-real-madrid-finale-2016-capitano-campo%2F&psig=AOvVaw0c_HhuDyMrc8Ayh88V929k&ust=1685672359619000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMj4lIOBof8CFQAAAAAdAAAAABAJ",
                            Nome = "Bola",
                            Preco = 69.2m
                        },
                        new
                        {
                            Id = 4L,
                            Categoria = "Esoporte",
                            Descricao = "Camisa Boston Celtics",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.aswracing.com.br%2Fcalca-asw-image-minimal-23-a1048723-p4013646&psig=AOvVaw1isNPh-QwGdSv-p919sBfC&ust=1685672108553000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIiL64qAof8CFQAAAAAdAAAAABAE",
                            Nome = "Camisa Boston",
                            Preco = 169.2m
                        },
                        new
                        {
                            Id = 5L,
                            Categoria = "Esporte",
                            Descricao = "Camisa N1 Ec Vitoria",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fecvitoria.com.br%2F&psig=AOvVaw18GzKbptFY0jKW12awdw5D&ust=1685672284695000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCMiXzd-Aof8CFQAAAAAdAAAAABAE",
                            Nome = "Camisa Vitoria",
                            Preco = 269.2m
                        },
                        new
                        {
                            Id = 6L,
                            Categoria = "Banho",
                            Descricao = "Tolha de banho",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.zelo.com.br%2Fkit-toalha-banho-e-toalha-rosto-zelo-classic-gramatura-400g-m-fendi-p1000952&psig=AOvVaw0nGAUY5FxvJk9eWeaPRg9O&ust=1685672244467000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIijmsyAof8CFQAAAAAdAAAAABAE",
                            Nome = "Toalha",
                            Preco = 29.2m
                        },
                        new
                        {
                            Id = 7L,
                            Categoria = "Vestimenta",
                            Descricao = "Cueca Box",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bigburgplussize.com.br%2Fcueca-boxer-algodao-max-pr-14797-rim-702-p53921&psig=AOvVaw1aKrmaFO9njjVfH3-DoAj7&ust=1685672201709000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCOiy87eAof8CFQAAAAAdAAAAABAE",
                            Nome = "Cueca",
                            Preco = 9.2m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
